#ifndef __ERRORNO
#define __ERRORNO


#define ERROR_SUCCESS					0
#define ERROR_INVALID_FUNCTION			1
#define ERROR_FILE_NOT_FOUND			2
#define ERROR_NOT_ENOUGH_MEMORY			8
#define ERROR_INVALID_DATA				13
#define ERROR_BAD_LENGTH				24
#define ERROR_READ_FAULT				30
#define ERROR_NOT_SUPPORTED				50
#define ERROR_INVALID_PARAMETER			87
#define ERROR_NET_WRITE_FAULT			88
#define ERROR_DISK_FULL					112
#define ERROR_INSUFFICIENT_BUFFER		122
#define ERROR_FILE_INVALID				1006
#define ERROR_CANCELLED					1223
#define ERROR_CONNECTION_INVALID		1229
#define ERROR_CONNECTION_ABORTED		1236
#define ERROR_INTERNAL_ERROR			1359
#define ERROR_TIMEOUT					1460

#endif
